export interface ITrxTypee{
    type :number,
   caseNo?:number,
    name : string,
    nameLat :string,
    showBalanceYN? :boolean,
    invoiceYN? :boolean,
    invoiceSafeYN? :boolean,
    gInvoice? :boolean,
    clcSalesTax? :boolean| null,
    clcSalesTaxAfterDis? :boolean| null,
    showDisAmount? :boolean | null,
    showDicPercent? :boolean | null,
    showTaxPercent? :boolean | null,
    dstoreCode? :number | null,
    dCustCode? :number | null,
    lowBlances? :boolean | null,
    disablePrice?:boolean | null,
}